{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3d971c9f-9b07-4388-b358-53f222d477ff",
   "metadata": {},
   "outputs": [],
   "source": [
    "from fastapi import FastAPI, Query\n",
    "from pydantic import BaseModel, Field\n",
    "from typing import Optional, List\n",
    " \n",
    "app = FastAPI()\n",
    "\n",
    "# ══ PYDANTIC MODEL ════════════════════════════════════════════════\n",
    "class OrderRequest(BaseModel):\n",
    "    customer_name:    str = Field(..., min_length=2, max_length=100)\n",
    "    product_id:       int = Field(..., gt=0)\n",
    "    quantity:         int = Field(..., gt=0, le=100)\n",
    "    delivery_address: str = Field(..., min_length=10)\n",
    " \n",
    "# Q3 - Accept Customer Feedback\n",
    "class CustomerFeedback(BaseModel):\n",
    "    customer_name: str            = Field(..., min_length=2, max_length=100)\n",
    "    product_id:   int            = Field(..., gt=0)\n",
    "    rating:       int            = Field(..., ge=1, le=5)\n",
    "    comment:      Optional[str]  = Field(None, max_length=300)\n",
    "\n",
    "# Q5 - Validate & Place a Bulk Order\n",
    "class OrderItem(BaseModel):\n",
    "    product_id: int = Field(..., gt=0)\n",
    "    quantity:   int = Field(..., gt=0, le=50)\n",
    "\n",
    "class BulkOrder(BaseModel):\n",
    "    company_name:  str           = Field(..., min_length=2)\n",
    "    contact_email: str           = Field(..., min_length=5)\n",
    "    items:         List[OrderItem] = Field(..., min_items=1)\n",
    "\n",
    "# ══ DATA ══════════════════════════════════════════════════════════\n",
    "products = [\n",
    "    {'id':1,'name':'Wireless Mouse','price':499,'category':'Electronics','in_stock':True},\n",
    "    {'id':2,'name':'Notebook',      'price': 99,'category':'Stationery', 'in_stock':True},\n",
    "    {'id':3,'name':'USB Hub',        'price':799,'category':'Electronics','in_stock':False},\n",
    "    {'id':4,'name':'Pen Set',         'price': 49,'category':'Stationery', 'in_stock':True},\n",
    "]\n",
    "orders = []\n",
    "feedback = []\n",
    "order_counter = 1\n",
    " \n",
    "# ══ HELPER FUNCTIONS ══════════════════════════════════════════════\n",
    " \n",
    "def find_product(product_id: int):\n",
    "    \"\"\"Search products list by ID. Returns product dict or None.\"\"\"\n",
    "    for p in products:\n",
    "        if p['id'] == product_id:\n",
    "            return p\n",
    "    return None\n",
    " \n",
    "def calculate_total(product: dict, quantity: int) -> int:\n",
    "    \"\"\"Multiply price by quantity and return total.\"\"\"\n",
    "    return product['price'] * quantity\n",
    " \n",
    "def filter_products_logic(category=None, min_price=None,\n",
    "                          max_price=None, in_stock=None):\n",
    "    \"\"\"Apply filters and return matching products.\"\"\"\n",
    "    result = products\n",
    "    if category  is not None:\n",
    "        result = [p for p in result if p['category'] == category]\n",
    "    if min_price is not None:\n",
    "        result = [p for p in result if p['price'] >= min_price]\n",
    "    if max_price is not None:\n",
    "        result = [p for p in result if p['price'] <= max_price]\n",
    "    if in_stock  is not None:\n",
    "        result = [p for p in result if p['in_stock'] == in_stock]\n",
    "    return result\n",
    " \n",
    "# ══ ENDPOINTS ═════════════════════════════════════════════════════\n",
    "# ROUTE ORDER RULE:\n",
    "#   Fixed routes  (/filter, /compare)  must come BEFORE\n",
    "#   Variable route (/products/{product_id})\n",
    "# ═════════════════════════════════════════════════════════════════\n",
    " \n",
    "# ── Day 1 ─────────────────────────────────────────────────────────\n",
    "@app.get('/')\n",
    "def home():\n",
    "    return {'message': 'Welcome to our E-commerce API'}\n",
    " \n",
    "@app.get('/products')\n",
    "def get_all_products():\n",
    "    return {'products': products, 'total': len(products)}\n",
    " \n",
    "# ── Day 2: Query Parameters ────────────────────────────────────────\n",
    "# NOTE: /filter, /compare, /summary must come BEFORE /{product_id}\n",
    "\n",
    "@app.get('/products/filter')\n",
    "def filter_products(\n",
    "    category:  str  = Query(None, description='Electronics or Stationery'),\n",
    "    min_price: int  = Query(None, description='Minimum price'),\n",
    "    max_price: int  = Query(None, description='Maximum price'),\n",
    "    in_stock:  bool = Query(None, description='True = in stock only'),\n",
    "):\n",
    "    result = filter_products_logic(category, min_price, max_price, in_stock)\n",
    "\n",
    "    # Q1 - Filter Products by Minimum Price\n",
    "    if min_price:\n",
    "        result = [p for p in result if p['price'] >= min_price]\n",
    "\n",
    "    if max_price:\n",
    "        result = [p for p in result if p['price'] <= max_price]\n",
    "\n",
    "    return {'filtered_products': result, 'count': len(result)}\n",
    " \n",
    "# ── Day 3: Compare (fixed route — must stay BEFORE /{product_id}) ─\n",
    "@app.get('/products/compare')\n",
    "def compare_products(\n",
    "    product_id_1: int = Query(..., description='First product ID'),\n",
    "    product_id_2: int = Query(..., description='Second product ID'),\n",
    "):\n",
    "    p1 = find_product(product_id_1)\n",
    "    p2 = find_product(product_id_2)\n",
    "    if not p1:\n",
    "        return {'error': f'Product {product_id_1} not found'}\n",
    "    if not p2:\n",
    "        return {'error': f'Product {product_id_2} not found'}\n",
    "    cheaper = p1 if p1['price'] < p2['price'] else p2\n",
    "    return {\n",
    "        'product_1':    p1,\n",
    "        'product_2':    p2,\n",
    "        'better_value': cheaper['name'],\n",
    "        'price_diff':   abs(p1['price'] - p2['price']),\n",
    "    }\n",
    "\n",
    "# Q4 - Build a Product Summary Dashboard\n",
    "# endpoint: GET /products/summary\n",
    "@app.get(\"/products/summary\")\n",
    "def product_summary():\n",
    "    in_stock   = [p for p in products if     p[\"in_stock\"]]\n",
    "    out_stock  = [p for p in products if not p[\"in_stock\"]]\n",
    "    expensive  = max(products, key=lambda p: p[\"price\"])\n",
    "    cheapest   = min(products, key=lambda p: p[\"price\"])\n",
    "    categories = list(set(p[\"category\"] for p in products))\n",
    "    return {\n",
    "        \"total_products\":     len(products),\n",
    "        \"in_stock_count\":     len(in_stock),\n",
    "        \"out_of_stock_count\": len(out_stock),\n",
    "        \"most_expensive\":     {\"name\": expensive[\"name\"], \"price\": expensive[\"price\"]},\n",
    "        \"cheapest\":           {\"name\": cheapest[\"name\"],  \"price\": cheapest[\"price\"]},\n",
    "        \"categories\":         categories,\n",
    "    }\n",
    " \n",
    "# ── Day 1: Path Parameter (variable — always AFTER all fixed routes)\n",
    "@app.get('/products/{product_id}')\n",
    "def get_product(product_id: int):\n",
    "    product = find_product(product_id)\n",
    "    if not product:\n",
    "        return {'error': 'Product not found'}\n",
    "    return {'product': product}\n",
    " \n",
    "# ── Day 2: POST + Pydantic ─────────────────────────────────────────\n",
    "@app.post('/orders')\n",
    "def place_order(order_data: OrderRequest):\n",
    "    global order_counter\n",
    " \n",
    "    product = find_product(order_data.product_id)\n",
    "    if not product:\n",
    "        return {'error': 'Product not found'}\n",
    " \n",
    "    if not product['in_stock']:\n",
    "        return {'error': f\"{product['name']} is out of stock\"}\n",
    " \n",
    "    total = calculate_total(product, order_data.quantity)\n",
    " \n",
    "    order = {\n",
    "        'order_id':         order_counter,\n",
    "        'customer_name':    order_data.customer_name,\n",
    "        'product':          product['name'],\n",
    "        'quantity':         order_data.quantity,\n",
    "        'delivery_address': order_data.delivery_address,\n",
    "        'total_price':      total,\n",
    "        'status':           'pending',\n",
    "    }\n",
    "    orders.append(order)\n",
    "    order_counter = order_counter + 1\n",
    "    return {'message': 'Order placed successfully', 'order': order}\n",
    " \n",
    "@app.get('/orders')\n",
    "def get_all_orders():\n",
    "    return {'orders': orders, 'total_orders': len(orders)}\n",
    " \n",
    "    return {'message':'Order placed successfully','order':order}\n",
    "\n",
    "@app.get('/orders')\n",
    "def get_all_orders():\n",
    "    return {'orders': orders, 'total_orders': len(orders)}\n",
    "\n",
    "# Q2 - Get Only the Price of a Product\n",
    "# endpoint: GET /products/{product_id}/price\n",
    "@app.get(\"/products/{product_id}/price\")\n",
    "def get_product_price(product_id: int):\n",
    "    for product in products:\n",
    "        if product[\"id\"] == product_id:\n",
    "            return {\"name\": product[\"name\"], \"price\": product[\"price\"]}\n",
    "    return {\"error\": \"Product not found\"}\n",
    "\n",
    "# Q3 - endpoint POST /feedback\n",
    "@app.post(\"/feedback\")\n",
    "def submit_feedback(data: CustomerFeedback):\n",
    "    feedback.append(data.dict())\n",
    "    return {\n",
    "        \"message\":        \"Feedback submitted successfully\",\n",
    "        \"feedback\":       data.dict(),\n",
    "        \"total_feedback\": len(feedback),\n",
    "    }\n",
    "\n",
    "# Q5 - endpoint POST /orders/bulk\n",
    "@app.post(\"/orders/bulk\")\n",
    "def place_bulk_order(order: BulkOrder):\n",
    "    confirmed, failed, grand_total = [], [], 0\n",
    "    for item in order.items:\n",
    "        product = next((p for p in products if p[\"id\"] == item.product_id), None)\n",
    "        if not product:\n",
    "            failed.append({\"product_id\": item.product_id, \"reason\": \"Product not found\"})\n",
    "        elif not product[\"in_stock\"]:\n",
    "            failed.append({\"product_id\": item.product_id, \"reason\": f\"{product['name']} is out of stock\"})\n",
    "        else:\n",
    "            subtotal = product[\"price\"] * item.quantity\n",
    "            grand_total += subtotal\n",
    "            confirmed.append({\"product\": product[\"name\"], \"qty\": item.quantity, \"subtotal\": subtotal})\n",
    "    return {\"company\": order.company_name, \"confirmed\": confirmed,\n",
    "            \"failed\": failed, \"grand_total\": grand_total}\n",
    "\n",
    "# New GET by order ID:\n",
    "@app.get(\"/orders/{order_id}\")\n",
    "def get_order(order_id: int):\n",
    "    for order in orders:\n",
    "        if order[\"order_id\"] == order_id:\n",
    "            return {\"order\": order}\n",
    "    return {\"error\": \"Order not found\"}\n",
    "\n",
    "# PATCH to confirm:\n",
    "@app.patch(\"/orders/{order_id}/confirm\")\n",
    "def confirm_order(order_id: int):\n",
    "    for order in orders:\n",
    "        if order[\"order_id\"] == order_id:\n",
    "            order[\"status\"] = \"confirmed\"\n",
    "            return {\"message\": \"Order confirmed\", \"order\": order}\n",
    "    return {\"error\": \"Order not found\"}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "956cd49a-06c0-4d06-8653-274a53d758ea",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
